# Example comparison code for ROUGE
baseline_summary = "summary generated by baseline model"
rl_summary = "summary generated by your RL model"

score_baseline = scorer.score(reference_text, baseline_summary)
score_rl = scorer.score(reference_text, rl_summary)

print("Baseline ROUGE:", score_baseline)
print("RL Model ROUGE:", score_rl)
